export const CHANGE_HOT_ALBUMS_LIST = 'album/CHANGE_HOT_ALBUMS_LIST'
export const CHANGE_ALL_ALBUMS_LIST = 'album/CHANGE_ALL_ALBUMS_LIST'
export const CHANGE_ALL_ALBUMS_TOTAL = 'album/CHANGE_ALL_ALBUMS_TOTAL'