export const CHANGE_CURRENT_INDEX = 'ranking/CHANGE_CURRENT_INDEX'
export const CHANGE_RANKING_BAR_LIST = 'ranking/CHANGE_RANKING_BAR_LIST'
export const CHANGE_RANKING_DETAIL_LIST = 'ranking/CHANGE_RANKING_DETAIL_LIST'